### ISSUE TITLE
I'd be down to help build this out.

### ISSUE THREAD

**Issue by r0zar** [robertDurst/lightning-app-poker#41]
How's the progress going so far?

Thanks,
RWR

**Comment by r0zar** [comment]
I think a cool game is exactly what lightning needs to take off right now.

Poker makes perfect sense as you know since it can be fully decentralized with using channels to create poker 'tables'. Cash is BTC on-chain and chips are BTC off-chain. Small satoshi blinds make great use of small instant payments.

**Comment by robertDurst** [comment]
Hey @r0zar sorry for the slow response! 

We called it quits after we gave the demo for this -- in fact the last week was a straight sprint so much of that code was pretty rough 😅 

Here is what we got done:
* Peer to peer game rooms via ngrok 
* Full poker rounds
* Lightning network payments (hardly though)

Technically, our Lightning Network setup does not work. Here is how we had it setup:

`A` will be the host.
`AA` will be the hosted "3rd party" wallet.
`B` will be a player.
`C` will be a player.

1. A starts a game
2. A creates a boots up a new server and a new LN instance
3. A opens a channel with AA, pushing all A's funds to AA's side of the channel
4. B joins. B opens a channel with AA, pushing all B's funds to AA's side of the channel
5. C joins. C opens a channel with AA, pushing all C's funds to AA's side of the channel
6. A,B,C play a round.
7. AA pays the winner money back from their channel

Obviously this does not technically work. The issues we had when trying to figure out the LN setup were:
* how can everyone have a guaranteed payment path?
* a hub spoke model does not work because funds can't jump channels (if A pays B and C pays B, B can't pay C A+C funds)
* is the hub spoke model really decentralized and secure?

While this repo may serve as a model for creating a LN poker game in the future, due to being built on an old version of Lightning Lab's desktop app, and due to the crazy thrown together code during the last week of the sprint, I would recommend starting mostly from scratch.

**Comment by r0zar** [comment]
Wow thanks for writing this up!

Yeah I anticipated the set up would be similar, except the A would essentially be the "dealer" / host, and others would connect to them similar to how in LAN gaming scenarios, a player host and others would connect to their lobby. Was there some specific reason the (AA) node was needed for the setup? The host (A) should be able to advertise their node for others to connect. They would all need to be publicly reachable, but it wouldn't be fun it they weren't.

Yes- there are definitely some things that could be improved with the LN experience for this use case, namely splicing... with it, the problem of routing funds (and hub/spoke layout) around the table _should_ be eliminated.

Turns out I've been crazy busy too, but if do you want to take another swing at it let me know!
